INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06');
INSERT INTO area (name) VALUES('it');
INSERT INTO area (name) VALUES('personal');
INSERT INTO service (`code`, `name`, `detail`, `price`, `area_id`, `optional`) VALUES ('cod-it', 'seguridad informatica', 'ethical hacking y otros procedimientos', '4000', '1', '0');
INSERT INTO service (`code`, `name`, `detail`, `price`, `area_id`, `optional`) VALUES ('cod-it', 'sys admin', 'administracion de sistemas', '8400', '1', '0');
INSERT INTO service (`code`, `name`, `detail`, `price`, `area_id`, `optional`) VALUES ('cod-personal', 'contabilidad', 'contabilidad general', '4500', '2', '0');
INSERT INTO service (`code`, `name`, `detail`, `price`, `area_id`, `optional`) VALUES ('cod-personal', 'rrhh', 'recursos humanos', '3500', '2', '0');
